---
name: block-public
on:
  pull_request
jobs:
  check-for-public-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35.4.4
    - name: Check for any changes to public files
      # yamllint disable rule:indentation
      run: |
        for f in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ "${f}" != *"private"* ]]; then
            echo "${f} is a public file"
            exit 100
          fi
        done
      shell: bash
