name: WaitForJenkinsRun
on:
  pull_request
jobs:
  build:
    name: Wait For Jenkins To Finish
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: jenkins-build
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 86400
          intervalSeconds: 60
